### ISSUE TITLE
Szia Gábor!

### ISSUE THREAD

**Issue by Zumi007** [codesharp-hu/szamlazz-hu-sdk#10]
Van egy problémám, hogy az alábbi kódrészlettel állítom be a számla tételeit:

************************************************************************************
var request = new CreateInvoiceRequest();
            request.AuthenticationData.ApiKey = "*****";

            request.Header.IssueDate = DateTime.Now;
            request.Header.CompletionDate = DateTime.Now;
            request.Header.DueDate = DateTime.Now;
            request.Header.PaymentType = "Készpénz";
            request.Header.InvoiceNumberPrefix = "FRST1";

            request.Seller.BankName = "Our Bank";
            request.Seller.BankAccount = "11111111-22222222-33333333";

            request.Customer.Name = "Good Friend Inc.";
            request.Customer.CustomerAddress.PostalCode = "1132";
            request.Customer.CustomerAddress.City = "Budapest";
            request.Customer.CustomerAddress.StreetAddress = "Tárnoki út 23.";
            request.Customer.TaxNumber = "12345678-1-42";

            request.Settings.Electric = false;

            request.Items = new List<InvoiceItem> {
             new InvoiceItem
             {
                Name = "Citrom",
                Quantity = 11046M,
                UnitOfQuantity = "Dkg",
                UnitPrice = 20.96505522M, 
                VatRate = "27",
                NetPrice = 231580M, 
                VatAmount = 62526M, 
                GrossAmount = 294106M
             }
              };

            var api = new SzamlazzHuApi();
            var response = await api.CreateInvoice(request);
************************************************************************************
A számláz.hu -ról azzal a hibával jön vissza, hogy a nettó érték nem egyenlő a nettó egységár és a mennyiség szorzatával.
Van ötleted?

Köszi.
Zoli

**Comment by agabor** [comment]
Szia Zoli!
A UnitPrice-t 2 tizedes jegyre kerekítve adom át a számlázz.hu-nak, és szerintem ők se kezelnek ennél pontosabb összegeket. Ezeknél a számoknál ez már lényeges kerekítési hibát okoz. Ha ennyire pontosan szeretnéd árazni a citromot, akkor inkább mikrogrammban add meg az árát.

**Comment by Zumi007** [comment]
Hali! Köszönöm a gyors választ. Úgy sikerült megoldanom, hogy a createInvoiceRequest.sbn-ben átírtam a kerekítést
F6-ra. A szamlazz.hu nagyobb pontossággal számol. 
********************************************
<nettoEgysegar>{{ item.unit_price | math.format "F6" "en-US" }}</nettoEgysegar>
********************************************
Lehet, hogy célszerű lenne a tiédben is átírni.
Más:
Azt vettem észre hogy ha a termék nevében & szerepel akkor hibával végződik a számla felküldése.

Köszi:
Zoli

**Comment by agabor** [comment]
Szerintem nem életszerű ez a példa, én legalábbis nem láttam még olyat, hogy töredék forintban legyen megadva az ár. Euróban, dollárban is kerek centet lehet megadni, arra pedig ott a két tizedes jegy.
