### ISSUE TITLE
Speciális karakterek

### ISSUE THREAD

**Issue by pgeza** [codesharp-hu/szamlazz-hu-sdk#14]
Szia!

A vevő nevében levő speciális karatekere nekem elszáll az xml szerializás. Konkrétan a &-el van baja, így megy:
Replace("&", " & # 38;")

de ezek se mennek gondolom: https://docs.oracle.com/cd/A97335_02/apps.102/bc4j/developing_bc_projects/obcCustomXml.htm
Mondjuk a házszámban ilyen jel ritkán van de gondolom akkor már minden mezőben érdemes azt a konverziót megcsinálni.
Hacsak nem én szurtam el vmit...
Üdv,

**Comment by agabor** [comment]
Szia!

Jogos meglátás, valóban HTML enkódolni kellene a nevet és címet.
https://learn.microsoft.com/en-us/dotnet/api/system.web.httputility.htmlencode?view=net-7.0#system-web-httputility-htmlencode(system-string)
Van kedved egy pull requestet küldeni erre?

**Comment by pgeza** [comment]
Nem vagyok egy nagy pullrequester... látsz vmit? :)

**Comment by agabor** [comment]
#15 
Köszönöm szépen, de végül egy egyszerűbb megoldást választottam:
https://github.com/agabor/szamlazz-hu-sdk/commit/bd3664d604bffb8f25f58f94cdf484f8fb41738a
