### ISSUE TITLE
XLM válaszban spec karakterek

### ISSUE THREAD

**Issue by ghost** [codesharp-hu/szamlazz-hu-sdk#17]
A HttpUploadXmlFile hívásban nincs kezelve, ha az API válaszban ékezetes karakterek vannak pl hibaüzenet miatt, emiatt valahol az xml parse benyeli a hiba nagy részét és csak ennyi jön vissza:
"[ERR] Sz&aacute"	

A választ dekódolva már jó lesz (string xml = System.Web.HttpUtility.HtmlDecode(reader.ReadToEnd());  a 102. sorban)
"[ERR] Számla mentés sikertelen.\nA számla kelte csak a mai nap lehet: 2023.08.23..\r\n.........

**Comment by agabor** [comment]
Köszönöm a visszajelzést, javítottam az 1.4.2-es verzióban. Annyit módosítottam rajta, hogy csak hibás válasz esetén használom a HtmlDecode függvényt, mert egyéb esetben ezt az XML Parser megoldja.
