### ISSUE TITLE
Types should be enums or a should come from a static class

### ISSUE THREAD

**Issue by AnsweRRR** [codesharp-hu/szamlazz-hu-sdk#18]
Kicsit furcsa volt így hirtelen, hogy néhány property (pl. PaymentType, InvoiceType, stb.) sima stringként szerepel. Ebben tudnátok segíteni, hogy van-e esetleg valami indoka? Előre is köszi.

**Comment by agabor** [comment]
Nincs különösebb indoka. Ha szeretnéd, írd át, és nyiss egy pull request-et.

**Comment by AnsweRRR** [comment]
Rendben, köszi :)
